#
# Locations
#
LOCATION_REPORTED = 'report'
LOCATION_PRODUCTION = 'action'
LOCATION_TESTING = 'test'
LOCATION_DELIVERED = 'deliver'
LOCATION_DELETED = 'delete'

#
# Itemstate
#
ITEMSTATE_IDENTIFIED = 'ITEMSTATE_IDENTIFIED'
ITEMSTATE_ACTIONED = 'ITEMSTATE_ACTIONED'
ITEMSTATE_COMPLETED = 'ITEMSTATE_COMPLETED'
ITEMSTATE_VERIFIED = 'ITEMSTATE_VERIFIED'

#
# Mercurial
#
MERCURIAL_TIP_ID = 'MERCURIAL_TIP_ID'
MERCURIAL_CONNECTION_STRING = 'MERCURIAL_CONNECTION_STRING'
MERCURIAL_REPOSITORY_PATH = 'MERCURIAL_REPOSITORY_PATH'

#
# View Preferences
# (User specific)
#
VIEWPREFERENCES_DEFAULT_VIEWSTATE = 'VIEWPREFERENCES_DEFAULT_VIEWSTATE'